# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        TS\NaoBundle\Entity\User: plaintext
    
    role_hierarchy:
        ROLE_NATURALIST: [ROLE_BIRD_FANCIER]
        ROLE_ADMIN: [ROLE_NATURALIST, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: TS\NaoBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main

            form_login:
                login_path: ts_nao_login
                check_path: ts_nao_login_check
                default_target_path: ts_nao_dashboard
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret: '%secret%'

            logout:
                path: ts_nao_logout
                target: ts_nao_homepage

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_BIRD_FANCIER }