<?php

namespace TS\NaoBundle\Repository;

/**
 * TAXREFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAXREFRepository extends \Doctrine\ORM\EntityRepository
{
}
