<?php

namespace TS\NaoBundle\Repository;

/**
 * TAXREF_HABITATSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAXREF_HABITATSRepository extends \Doctrine\ORM\EntityRepository
{
}
