<?php

namespace TS\NaoBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUpgradeRequestList()
	{
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.grade IS NOT NULL');
		$result = $qb->getQuery()->getArrayResult();

		return $result;
	}
}
