ts_nao_homepage:
    path:     /
    defaults:
        _controller: TSNaoBundle:Search:index

ts_nao_registration:
    path: /registration
    defaults:
        _controller: TSNaoBundle:User:registration

ts_nao_login:
    path: /login
    defaults:
        _controller: TSNaoBundle:User:login

ts_nao_login_check:
    path: /login_check

ts_nao_logout:
    path: /logout

ts_nao_recovery:
    path: /recovery
    defaults:
        _controller: TSNaoBundle:User:recovery

ts_nao_reset_password:
    path: /reset-password/
    defaults:
        _controller: TSNaoBundle:User:resetPassword

ts_nao_delete_account:
    path: /account/delete-account
    defaults:
        _controller: TSNaoBundle:User:deleteAccount
    defaults: { _controller: TSNaoBundle:Search:index }

ts_nao_dashboard:
    path: /account
    defaults:
        _controller: TSNaoBundle:Account:dashboard

ts_nao_active_account:
    path: /active
    defaults:
        _controller: TSNaoBundle:Account:active

ts_nao_disabled:
    path: /disabled
    defaults:
        _controller: TSNaoBundle:Account:disabled

ts_nao_specimens_names:
  path: /specimens_name
  defaults: { _controller: TSNaoBundle:Search:loadSpecimens }
